### ISSUE TITLE
Improvement codice in sintassi ES6

### ISSUE THREAD

**Issue by steoo** [julianxhokaxhiu/PostEvent#1]
Alla linea 28 https://github.com/julianxhokaxhiu/PostEvent/blob/master/src/index.es6#L28 potrebbero essere fatti i seguenti miglioramenti:

```
trigger( name, params = null ){
    if ( name ) {
      let message = {
        name,
        params
      };
    /* ... */
}
```

Ovvero il parametro di default `null`e poi gli shorthands `name`e `params` che verrebbero tradotti in `name: name, params: params`

**Comment by julianxhokaxhiu** [comment]
Ottimo, grazie mille! Più tardi provvedo, se ti va di creare una PR accetto volentieri :)

**Comment by steoo** [comment]
Ok! Dopo provvedo a fare Fork e PR

**Comment by julianxhokaxhiu** [comment]
Grazie per la PR :)
